/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TroubleshootingRouteImport } from './routes/troubleshooting'
import { Route as PrerequisitesRouteImport } from './routes/prerequisites'
import { Route as Phase9RouteImport } from './routes/phase-9'
import { Route as Phase8RouteImport } from './routes/phase-8'
import { Route as Phase7RouteImport } from './routes/phase-7'
import { Route as Phase6RouteImport } from './routes/phase-6'
import { Route as Phase5RouteImport } from './routes/phase-5'
import { Route as Phase4RouteImport } from './routes/phase-4'
import { Route as Phase3RouteImport } from './routes/phase-3'
import { Route as Phase2RouteImport } from './routes/phase-2'
import { Route as Phase1RouteImport } from './routes/phase-1'
import { Route as Phase0RouteImport } from './routes/phase-0'
import { Route as HacksRouteImport } from './routes/hacks'
import { Route as CostRouteImport } from './routes/cost'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BestPracticesRouteImport } from './routes/best-practices'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const TroubleshootingRoute = TroubleshootingRouteImport.update({
  id: '/troubleshooting',
  path: '/troubleshooting',
  getParentRoute: () => rootRouteImport,
} as any)
const PrerequisitesRoute = PrerequisitesRouteImport.update({
  id: '/prerequisites',
  path: '/prerequisites',
  getParentRoute: () => rootRouteImport,
} as any)
const Phase9Route = Phase9RouteImport.update({
  id: '/phase-9',
  path: '/phase-9',
  getParentRoute: () => rootRouteImport,
} as any)
const Phase8Route = Phase8RouteImport.update({
  id: '/phase-8',
  path: '/phase-8',
  getParentRoute: () => rootRouteImport,
} as any)
const Phase7Route = Phase7RouteImport.update({
  id: '/phase-7',
  path: '/phase-7',
  getParentRoute: () => rootRouteImport,
} as any)
const Phase6Route = Phase6RouteImport.update({
  id: '/phase-6',
  path: '/phase-6',
  getParentRoute: () => rootRouteImport,
} as any)
const Phase5Route = Phase5RouteImport.update({
  id: '/phase-5',
  path: '/phase-5',
  getParentRoute: () => rootRouteImport,
} as any)
const Phase4Route = Phase4RouteImport.update({
  id: '/phase-4',
  path: '/phase-4',
  getParentRoute: () => rootRouteImport,
} as any)
const Phase3Route = Phase3RouteImport.update({
  id: '/phase-3',
  path: '/phase-3',
  getParentRoute: () => rootRouteImport,
} as any)
const Phase2Route = Phase2RouteImport.update({
  id: '/phase-2',
  path: '/phase-2',
  getParentRoute: () => rootRouteImport,
} as any)
const Phase1Route = Phase1RouteImport.update({
  id: '/phase-1',
  path: '/phase-1',
  getParentRoute: () => rootRouteImport,
} as any)
const Phase0Route = Phase0RouteImport.update({
  id: '/phase-0',
  path: '/phase-0',
  getParentRoute: () => rootRouteImport,
} as any)
const HacksRoute = HacksRouteImport.update({
  id: '/hacks',
  path: '/hacks',
  getParentRoute: () => rootRouteImport,
} as any)
const CostRoute = CostRouteImport.update({
  id: '/cost',
  path: '/cost',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BestPracticesRoute = BestPracticesRouteImport.update({
  id: '/best-practices',
  path: '/best-practices',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/architecture': typeof ArchitectureRoute
  '/best-practices': typeof BestPracticesRoute
  '/contact': typeof ContactRoute
  '/cost': typeof CostRoute
  '/hacks': typeof HacksRoute
  '/phase-0': typeof Phase0Route
  '/phase-1': typeof Phase1Route
  '/phase-2': typeof Phase2Route
  '/phase-3': typeof Phase3Route
  '/phase-4': typeof Phase4Route
  '/phase-5': typeof Phase5Route
  '/phase-6': typeof Phase6Route
  '/phase-7': typeof Phase7Route
  '/phase-8': typeof Phase8Route
  '/phase-9': typeof Phase9Route
  '/prerequisites': typeof PrerequisitesRoute
  '/troubleshooting': typeof TroubleshootingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/architecture': typeof ArchitectureRoute
  '/best-practices': typeof BestPracticesRoute
  '/contact': typeof ContactRoute
  '/cost': typeof CostRoute
  '/hacks': typeof HacksRoute
  '/phase-0': typeof Phase0Route
  '/phase-1': typeof Phase1Route
  '/phase-2': typeof Phase2Route
  '/phase-3': typeof Phase3Route
  '/phase-4': typeof Phase4Route
  '/phase-5': typeof Phase5Route
  '/phase-6': typeof Phase6Route
  '/phase-7': typeof Phase7Route
  '/phase-8': typeof Phase8Route
  '/phase-9': typeof Phase9Route
  '/prerequisites': typeof PrerequisitesRoute
  '/troubleshooting': typeof TroubleshootingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/architecture': typeof ArchitectureRoute
  '/best-practices': typeof BestPracticesRoute
  '/contact': typeof ContactRoute
  '/cost': typeof CostRoute
  '/hacks': typeof HacksRoute
  '/phase-0': typeof Phase0Route
  '/phase-1': typeof Phase1Route
  '/phase-2': typeof Phase2Route
  '/phase-3': typeof Phase3Route
  '/phase-4': typeof Phase4Route
  '/phase-5': typeof Phase5Route
  '/phase-6': typeof Phase6Route
  '/phase-7': typeof Phase7Route
  '/phase-8': typeof Phase8Route
  '/phase-9': typeof Phase9Route
  '/prerequisites': typeof PrerequisitesRoute
  '/troubleshooting': typeof TroubleshootingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/architecture'
    | '/best-practices'
    | '/contact'
    | '/cost'
    | '/hacks'
    | '/phase-0'
    | '/phase-1'
    | '/phase-2'
    | '/phase-3'
    | '/phase-4'
    | '/phase-5'
    | '/phase-6'
    | '/phase-7'
    | '/phase-8'
    | '/phase-9'
    | '/prerequisites'
    | '/troubleshooting'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/architecture'
    | '/best-practices'
    | '/contact'
    | '/cost'
    | '/hacks'
    | '/phase-0'
    | '/phase-1'
    | '/phase-2'
    | '/phase-3'
    | '/phase-4'
    | '/phase-5'
    | '/phase-6'
    | '/phase-7'
    | '/phase-8'
    | '/phase-9'
    | '/prerequisites'
    | '/troubleshooting'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/architecture'
    | '/best-practices'
    | '/contact'
    | '/cost'
    | '/hacks'
    | '/phase-0'
    | '/phase-1'
    | '/phase-2'
    | '/phase-3'
    | '/phase-4'
    | '/phase-5'
    | '/phase-6'
    | '/phase-7'
    | '/phase-8'
    | '/phase-9'
    | '/prerequisites'
    | '/troubleshooting'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ArchitectureRoute: typeof ArchitectureRoute
  BestPracticesRoute: typeof BestPracticesRoute
  ContactRoute: typeof ContactRoute
  CostRoute: typeof CostRoute
  HacksRoute: typeof HacksRoute
  Phase0Route: typeof Phase0Route
  Phase1Route: typeof Phase1Route
  Phase2Route: typeof Phase2Route
  Phase3Route: typeof Phase3Route
  Phase4Route: typeof Phase4Route
  Phase5Route: typeof Phase5Route
  Phase6Route: typeof Phase6Route
  Phase7Route: typeof Phase7Route
  Phase8Route: typeof Phase8Route
  Phase9Route: typeof Phase9Route
  PrerequisitesRoute: typeof PrerequisitesRoute
  TroubleshootingRoute: typeof TroubleshootingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/troubleshooting': {
      id: '/troubleshooting'
      path: '/troubleshooting'
      fullPath: '/troubleshooting'
      preLoaderRoute: typeof TroubleshootingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prerequisites': {
      id: '/prerequisites'
      path: '/prerequisites'
      fullPath: '/prerequisites'
      preLoaderRoute: typeof PrerequisitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phase-9': {
      id: '/phase-9'
      path: '/phase-9'
      fullPath: '/phase-9'
      preLoaderRoute: typeof Phase9RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phase-8': {
      id: '/phase-8'
      path: '/phase-8'
      fullPath: '/phase-8'
      preLoaderRoute: typeof Phase8RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phase-7': {
      id: '/phase-7'
      path: '/phase-7'
      fullPath: '/phase-7'
      preLoaderRoute: typeof Phase7RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phase-6': {
      id: '/phase-6'
      path: '/phase-6'
      fullPath: '/phase-6'
      preLoaderRoute: typeof Phase6RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phase-5': {
      id: '/phase-5'
      path: '/phase-5'
      fullPath: '/phase-5'
      preLoaderRoute: typeof Phase5RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phase-4': {
      id: '/phase-4'
      path: '/phase-4'
      fullPath: '/phase-4'
      preLoaderRoute: typeof Phase4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phase-3': {
      id: '/phase-3'
      path: '/phase-3'
      fullPath: '/phase-3'
      preLoaderRoute: typeof Phase3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phase-2': {
      id: '/phase-2'
      path: '/phase-2'
      fullPath: '/phase-2'
      preLoaderRoute: typeof Phase2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phase-1': {
      id: '/phase-1'
      path: '/phase-1'
      fullPath: '/phase-1'
      preLoaderRoute: typeof Phase1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phase-0': {
      id: '/phase-0'
      path: '/phase-0'
      fullPath: '/phase-0'
      preLoaderRoute: typeof Phase0RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hacks': {
      id: '/hacks'
      path: '/hacks'
      fullPath: '/hacks'
      preLoaderRoute: typeof HacksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cost': {
      id: '/cost'
      path: '/cost'
      fullPath: '/cost'
      preLoaderRoute: typeof CostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/best-practices': {
      id: '/best-practices'
      path: '/best-practices'
      fullPath: '/best-practices'
      preLoaderRoute: typeof BestPracticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ArchitectureRoute: ArchitectureRoute,
  BestPracticesRoute: BestPracticesRoute,
  ContactRoute: ContactRoute,
  CostRoute: CostRoute,
  HacksRoute: HacksRoute,
  Phase0Route: Phase0Route,
  Phase1Route: Phase1Route,
  Phase2Route: Phase2Route,
  Phase3Route: Phase3Route,
  Phase4Route: Phase4Route,
  Phase5Route: Phase5Route,
  Phase6Route: Phase6Route,
  Phase7Route: Phase7Route,
  Phase8Route: Phase8Route,
  Phase9Route: Phase9Route,
  PrerequisitesRoute: PrerequisitesRoute,
  TroubleshootingRoute: TroubleshootingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
